name: universal_dementia_detector
description: "Language-agnostic Speech Dementia Detector."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  record: ^5.0.5
  just_audio: ^0.9.38
  file_picker: ^9.0.0
  path_provider: ^2.1.3
  path: ^1.9.0
  http: ^1.0.0
  audio_waveforms: ^1.2.0
  fullscreen_window: ^1.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/cookie_test.png
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

l10n:
  arb-dir: lib/l10n
  template-arb-file: en.arb
  output-localization-file: lib\l10n\app_localizations.dart
  output-class: AppLocalizations
